CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

first_app/urls.py
from django.urls import path
from . import views

app_name = "first_app"

urlpatterns = [
    path('', views.index, name="index"),
    path('student_form/', views.student_form, name="student_form"),
    path('student_info<int:student_id>/',
         views.student_info, name="student_info"),
    path('student_update<int:student_id>/',
         views.student_update, name="student_update"),
    path('student_delete<int:student_id>/',
         views.student_delete, name="student_delete"),
]

first_app/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()

    # __str__(self) function represents the profile data title in the admin database
    def __str__(self):
        return str(self.pk) + " " + self.first_name + " " + self.last_name

first_app/forms.py
from django import forms
from first_app import models


class StudentForm(forms.ModelForm):
    class Meta:
        # taking all the fields and creating a form according to the Student object
        model = models.Student

        # telling django that we need all the fields to create the student form
        fields = "__all__"

        # that is how we can put bootstrap class as attributes to style the html form
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }

first_app/views.py
from django.shortcuts import render
from first_app import forms
from .models import Student

# Create your views here.


def index(request):
    # collecting all the students information in the student_list variable with the following statement
    student_list = Student.objects.all().order_by('first_name')
    diction = {
        'title': "Student List",
        'student_list': student_list,
    }
    # returning the index.html page with the list of students and the title
    # student_list will be handled in the html file
    return render(request, 'first_app/index.html', context=diction)


def student_form(request):
    form = forms.StudentForm()

    # (request.method == "POST") when user clicks on the submit button
    if request.method == "POST":
        form = forms.StudentForm(request.POST)

        if form.is_valid():
            # (commit = True) pushes the forms date into the database
            form.save(commit=True)
            return index(request)
            # calling index() function to return into the index page

    # Creating a student form and sending the to the user
    diction = {
        'title': "Student Form",
        'student_form': form,
    }
    return render(request, 'first_app/student_form.html', context=diction)


def student_info(request, student_id):
    # searching the student with the following statement
    student_info = Student.objects.get(pk=student_id)
    diction = {
        'student_info': student_info,
    }
    return render(request, 'first_app/student_info.html', context=diction)


def student_update(request, student_id):
    # finding the student by the following statement
    student_info = Student.objects.get(pk=student_id)

    # putting all the data into the form to edit that information
    form = forms.StudentForm(instance=student_info)

    # if user hits update button then the method will be "POST"
    if request.method == "POST":
        form = forms.StudentForm(request.POST, instance=student_info)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction = {
        'student_form': form,
    }
    # if the page reloads then return the same page with same data
    return render(request, 'first_app/student_update.html', context=diction)


def student_delete(request, student_id):
    # deleting the student by the following statement
    student = Student.objects.get(pk=student_id).delete()
    diction = {
        'delete_message': "Delete Done",
    }
    return render(request, 'first_app/student_delete.html', context=diction)

templates/first_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'first_app/base.css' %}">
    {% block styles %}
    {% endblock styles %}
    <title>{{ title }}</title>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:index' %}">Index</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:student_form' %}">Student Form</a>
        </li>
    </ul>
    {% block body %}
    {% endblock body %}
</body>
</html>

templates/first_app/index.html
{% extends 'first_app/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'first_app/index.css' %}">
{% endblock styles %}

{% block body %}
    {% csrf_token %}
    <h1>{{ title }}</h1>

    <div class="student-list-container">
    {% if student_list %}
        <ul class="student-list">
            {% comment %} using loop to show the list returned by the index() function from views.py {% endcomment %}
            {% for student in student_list %}
                <li class="list-item"><a href="{% url 'first_app:student_info' student_id=student.id %}">{{student.first_name}} {{student.last_name}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <h3>No Student</h3>
    {% endif %}
    </div>
    
{% endblock body %}

templates/first_app/student_delete.html
{% extends 'first_app/base.html' %}

{% block body %}
    <div class="alert alert-danger">{{ delete_message }}</div>
{% endblock body %}

templates/first_app/student_form.html
{% extends 'first_app/base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'first_app/student_form.css' %}">
{% endblock styles %}

{% block body %}
    <h1>Student Form</h1>
    <div class="form-group">
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} as_p makes the form component varticaly arranged {% endcomment %}
            {{ student_form.as_p }}
            
            <button type="submit" class="btn btn-success">Add Student</button>
            {% comment %} <input type="submit" name="submit" value="Add Student"> {% endcomment %}
        </form>
    </div>
{% endblock body %}

templates/first_app/student_info.html
{% extends 'first_app/base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'first_app/student_info.css' %}">
{% endblock styles %}

{% block body %}
    <h1>Student Information</h1>

    <div class="info-container">
        <h3>Student ID: {{student_info.id}}</h3>
        <h3>student Name: {{student_info.first_name}} {{student_info.last_name}}</h3>
        <h3>Email: {{student_info.email}}</h3>
        <h3>Phone: {{student_info.phone}}</h3>
    </div>

    <div class="button-container">
        <a href="{% url 'first_app:student_update' student_id=student_info.id %}" class="btn btn-primary">Update</a>
        <a href="{% url 'first_app:student_delete' student_id=student_info.id %}" class="btn btn-danger">Delete</a>
    </div>
{% endblock body %}

templates/first_app/student_update.html
{% extends 'first_app/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'first_app/student_update.css' %}">
{% endblock styles %}

{% block body %}
    <h1>Student Update</h1>

    <div class="form-group">
        <form action="" method="POST">
            {{student_form.as_p}}
            {% csrf_token %}
            <button type="submit" class="btn btn-warning">Update Student</button>
            {% comment %} <input type="submit" value="update"> {% endcomment %}
        </form>
    </div>
{% endblock body %}